[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "print-guard"
version = "0.1.0"
description = "PrintGuard - Real-time Defect Detection on Edge-devices"
authors = [
    { name = "Oliver Bravery", email = "dev@oliverbravery.uk" }
]
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "pywebpush",
    "apscheduler",
    "python-dotenv",
    "torch",
    "torchvision",
    "pillow",
    "opencv-python",
    "python-multipart",
    "keyring",
    "trustme"
]

[project.scripts]
print-guard = "print_guard.app:run"

[tool.black]
line-length = 88

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = ["print_guard", "print_guard.*", "protonets", "protonets.*"]

[tool.setuptools.package-data]
"print_guard" = [
    "static/**/*",
    "templates/**/*",
    "model/**/*"
]