name: Issue triage

on:
  issues:
    types: [opened]

permissions:
  contents: read

jobs:
  label:
    name: label
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - run: >-
          gh issue edit "$ISSUE_NUMBER" --repo "$GITHUB_REPOSITORY" --add-label "status: needs triage"
        env:
          GH_TOKEN: ${{ github.token }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
